FROM bitwalker/alpine-elixir:1.5.1

ENV HOME=/opt/app/ TERM=xterm

RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /opt/app

ENV MIX_ENV=prod

RUN mkdir config
COPY config/* config/
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

# wut aboot assets?

COPY . .

RUN mix release --env=prod --verbose
