FROM bitwalker/alpine-elixir-phoenix:1.5.0

WORKDIR /opt/app

ENV MIX_ENV=prod

RUN mkdir config
COPY config/* config/
COPY mix.exs mix.lock ./
RUN mix do deps.get, deps.compile

RUN mkdir assets
COPY assets/* assets/
WORKDIR /opt/app/assets
RUN npm install

WORKDIR /opt/app
COPY . .

WORKDIR /opt/app/assets
RUN brunch build --production

WORKDIR /opt/app
RUN mix phx.digest
RUN mix release --env=prod --verbose
